[project]
name = "gestort"
version = "0.1.0"
description = "Sistema de Gestión de Laboratorios"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python>=9.7.0",
    "python-dotenv>=1.2.2",
    "tkcalendar>=1.6.1",
]

[project.scripts]
gestort = "src.main:main"  # 👈 Cambiado de "app" a "gestort" o mantén "app"

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["."]

